### ISSUE TITLE
Does this contain the most up-to-date MPEA data?

### ISSUE THREAD

**Issue by sgbaird** [CitrineInformatics/MPEA_dataset#19]
i.e. same as what's available on the Citrine Platform

**Comment by ckborg** [comment]
Hi @sgbaird can you link me to which data you're referring to? The best way to access the most up-to-date dataset from this paper is currently on [Figshare](https://figshare.com/articles/dataset/Expanded_dataset_of_mechanical_properties_and_observed_phases_of_multi-principal_element_alloys/12642953).

**Comment by sgbaird** [comment]
Thanks!

- https://citrine.io/expanded-dataset-of-mechanical-properties-and-observed-phases-of-multi-principal-element-alloys/
- https://citrine.io/tag/mpea-database/
- https://citrination.com/datasets/190954/
